### ISSUE TITLE
VERSIONINFO block contains RealDimensions Software, LLC for our app

### ISSUE THREAD

**Issue by riverar** [chocolatey/home#108]
When shimgen generates a shim for our app, it appears to generate a VERSIONINFO block with the following contents:

```
BLOCK "StringFileInfo"
{
	BLOCK "000004b0"
	{
		VALUE "Comments", "EarTrumpet"
		VALUE "CompanyName", "File-New-Project"
		VALUE "FileDescription", "EarTrumpet - shim"
		VALUE "FileVersion", "2.1.9.0"
		VALUE "InternalName", "EarTrumpet.exe"
		VALUE "LegalCopyright", "Copyright \xA9 2013 - 2017 RealDimensions Software, LLC"
		VALUE "OriginalFilename", "EarTrumpet.exe"
		VALUE "ProductName", "EarTrumpet"
		VALUE "ProductVersion", "2.1.9+Branch.master.Sha.36e716c7fe4b375274f20229431f0501fe130460 - shim 0.8.1"
		VALUE "Assembly Version", "2.1.9.0"
	}
}
```

`RealDimensions Software, LLC` is unknown to me and does not hold copyright of anything EarTrumpet related. It also uses our app icon, of which `RealDimensions Software, LLC` has no license for as far as I know.

I presume this copyright notice was meant to govern the shim itself. If that's the case, I recommend the shim take over more of the fields here (e.g. Company Name, Product Name) to distinguish itself from our software.

Suggestion 1:

* Product Name: `Chocolatey shim for EarTrumpet`
* Copyright: `Copyright \xA9 2013 - 2017 RealDimensions Software, LLC`
* Company Name: `RealDimensions Software, LLC`
* Comments: `<blank>`
* File Description: `<blank>` or `<product name>`

Suggestion 2:
Perhaps copy the original Copyright metadata, then tack `, Copyright \xA9 2013 - 2017 RealDimensions Software, LLC` onto the end.

Suggestion 3:
Copy the original Copyright metadata, remove all your own copyright notices. These notices are not legally required.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/shimgen/-/issues/1) by [Unito](https://www.unito.io)
┆Milestone: 1.0.0

**Comment by gep13** [comment]
Based on some changes happening to the Chocolatey repositories, this issue has been moved from the chocolatey/shimgen repository to the chocolatey/home repository.
