### ISSUE TITLE
Update fallback Chocolatey logo

### ISSUE THREAD

**Issue by pauby** [chocolatey/home#112]
Shimgen will try to use the logo of the executable it is shimming. However, if it cannot do that, it falls back to using a default icon of the Chocolatey logo. This logo is the old Chocolatey logo. 

Update the default icon Chocolatey logo to be the new logo.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/shimgen/-/issues/5) by [Unito](https://www.unito.io)
┆Milestone: 1.0.0

**Comment by gep13** [comment]
Based on some changes happening to the Chocolatey repositories, this issue has been moved from the chocolatey/shimgen repository to the chocolatey/home repository.
