### ISSUE TITLE
Feature-Request: Provide a parameter to switch versions of side-by-side installation via choco

### ISSUE THREAD

**Issue by DenWin** [chocolatey/home#120]
Assuming we have installed different versions of a package using choco:

```bash
choco install package --version 1.2.3 -my
choco install package --version 2.0.0 -my
```

It would be nice to allow using the same shim-file with a version parameter:

```bash
$ package --shimgen-help
[shim]:
=========
Shim Help
=========

This is a shim, generated by Chocolatey's ShimGenerator (shimgen).
This shim calls a target with the following settings:
 Target: 'C:\ProgramData\chocolatey\lib\package.2.0.0\tools\package.exe'
 Target exists: 'True'
 Working directory: 'C:\WINDOWS\system32'
 GUI: 'False'
 Wait for exit: 'True'
 command (optional): ''
```

```bash
$ package -packageArgs --shimgen-version 1.2.3  --shimgen-help
[shim]:
=========
Shim Help
=========

This is a shim, generated by Chocolatey's ShimGenerator (shimgen).
This shim calls a target with the following settings:
 Target: 'C:\ProgramData\chocolatey\lib\package.1.2.3\tools\package.exe'
 Target exists: 'True'
 Working directory: 'C:\WINDOWS\system32'
 GUI: 'False'
 Wait for exit: 'True'
 command (optional): ''
```

It should also work if the target is  `Target: 'C:\ProgramData\chocolatey\lib\package\tools\package.exe'`

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/shimgen/-/issues/9) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
Based on some changes happening to the Chocolatey repositories, this issue has been moved from the chocolatey/shimgen repository to the chocolatey/home repository.

**Comment by pauby** [comment]
As we plan to [deprecate side-by-side installs](https://github.com/chocolatey/choco/issues/2787#issuecomment-1295013671) in version 2.0.0 of Chocolatey CLI, I'm going to go ahead and close this issue.
