### ISSUE TITLE
Contact link in shimgen license file broken.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/home#132]
http://ferventcoder.com/contact.aspx returns a 500 server error

Via [shimgen.license.txt](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/tools/shimgen.license.txt)
then as directed go to http://ferventcoder.com and then click on the contact link.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/shimgen/-/issues/25) by [Unito](https://www.unito.io)
┆Milestone: 1.0.0

**Comment by gep13** [comment]
Based on some changes happening to the Chocolatey repositories, this issue has been moved from the chocolatey/shimgen repository to the chocolatey/home repository.
