### ISSUE TITLE
Discord isn't easily discoverable

### ISSUE THREAD

**Issue by jsoref** [chocolatey/home#140]
## Is Your Feature Request Related To A Problem? Please describe.

I tried to find a place to discuss Chocolatey. I tried a number of times. I really couldn't find it. It is not visually discoverable. And it's hardly 

## Describe The Solution. Why is it needed?

1. Consider adding a tile in the [Contact page](https://chocolatey.org/contact/) for Discord
2. Spell out words (I'm discovering that I'm basically icon ignorant)
3. Add a section for `Community Chat (Discord)` to the https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md page (the page is too long) and make all of the current `community chat` items on the page just link to that section.
   - As a bonus, this will fix the inconsistent items:
     > or through [Community Chat](https://ch0.co/community-support)
     > in Community chat
     > the Community Chat conversation
4. Add a textual item for Community Chat (Discord) to https://community.chocolatey.org/
5. Consider adding textual items to the Community drop down in:
    <img width="890" alt="image" src="https://user-images.githubusercontent.com/2119212/156943389-245b8041-1c4c-4fef-8b8b-daa15fbf37ef.png">

 

## Additional Context.

* I tried clicking [Contact Us](https://chocolatey.org/contact/)
  <img width="882" alt="image" src="https://user-images.githubusercontent.com/2119212/156942645-1660cf26-45d0-42f0-9168-b0290ea3e3ee.png">

  Which doesn't have a link to Discord.

* I searched for `Chat` and various other keywords, and none of them worked.

   While it's _technically_ possible to discover that there's a chat bubble, it doesn't have hover text...
   <img width="207" alt="image" src="https://user-images.githubusercontent.com/2119212/156942680-f63e373d-c679-4703-8257-01f59a817aea.png">

   There *is* aria content, so if I'm willing to wait for VoiceOver to read the *entire* page, I might eventually get to `Connect with Chocolatey on Community Chat`, but it's a tiny bubble, and it's unlikely that I'd encounter it if I tried blindly scanning around with my finger.

* I scanned the readme from https://github.com/chocolatey/choco/

* I'm fairly certain I scanned the ToC of https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md#contributing and didn't see Chat/Discord/IRC/Slack/anything I recognize.

---

For comparison,

At the top of https://www.powerdns.com/, there's a link:
[Open Source](https://www.powerdns.com/opensource.html)

On that page, there's an item:
* IRC (instant messaging)
  * We hang out in #powerdns on OFTC ([irc.oftc.net](https://www.oftc.net/)).

Searching for `irc` or `messaging` will quickly find what I'm looking for. It's also in the main text, so I'll quickly find it by scanning.

At the top of https://www.jenkins.io/, there's a (JavaScript required...) item `Community` which when clicked yields:
[Chat](https://www.jenkins.io/chat/)

On that page, the keywords I'd expect to see (Gitter, IRC) are in flow. As is a reference to Slack with links to join Slacks.

Argo project has a slack icon in the top bar:
https://argoproj.github.io/

Note that Google search for `argoproj + slack` yields a slack invite page.
Google search for `chocolatey + discord` yields a package for installing some kind of discord using choco.

For mastodon, the main project readme has a reference in plain text:
https://github.com/mastodon/mastodon#contributing

**Comment by pauby** [comment]
I wanted to address some of this as I think there is a misunderstanding, some learnings for us and some incorrect information.

> Consider adding a tile in the [Contact page](https://chocolatey.org/contact/) for Discord

The community website is community.chocolatey.org. The website for the commercial edition of Chocolatey is at chocolatey.org, and the contact us options are based around that.

> Spell out words (I'm discovering that I'm basically icon ignorant)

We use `Community Chat` in many places instead of specific tools. Some people have no idea what Discord or Gitter (which we used previously) are. So, we use the words `Community Chat` on purpose, as we believe that's what people would search for. If we have missed, please let us know, and we can update those.

> Add a section for Community Chat (Discord) to the https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md 

We do highlight `Community Chat` [here](https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md?plain=1#L100) with a link to the Discord server. We also mention it [here](https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md?plain=1#L101), but without a link (as it's linked in the line above).

>  As a bonus, this will fix the inconsistent items:
> 
>        or through [Community Chat](https://ch0.co/community-support)
>        in Community chat
>        the Community Chat conversation

As they all say `Community Chat` I'm unsure how they are inconsistent?

> Add a textual item for Community Chat (Discord) to https://community.chocolatey.org/

Can you clarify what you mean?

> Consider adding textual items to the Community drop down in:

That is a good idea. I've raised #146 for this.

> While it's technically possible to discover that there's a chat bubble, it doesn't have hover text...

That is something we missed. I've raised #147 for this.

> I scanned the readme from https://github.com/chocolatey/choco/

We talk about that [here](https://github.com/chocolatey/choco/#chat-room) and have it in the TOC at the top too. However, the link is a button - does that not work for you?

> I'm fairly certain I scanned the ToC of https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md#contributing and didn't see Chat/Discord/IRC/Slack/anything I recognize.

It's not mentioned in the TOC. The Contributing doc is for Contributing to the Chocolatey CLI software. So it talks about how to setup your development environment, commits, code styles etc.

**Comment by jsoref** [comment]
> The community website is community.chocolatey.org. The website for the commercial edition of Chocolatey is at chocolatey.org, and the contact us options are based around that.

Yeah. I understand the distinction exists. As a fumbling user who's scanning for keywords, that distinction hurt me.

> We use `Community Chat` in many places instead of specific tools. 

I appreciate having a generic term that helps people who don't know the technology. I'm partially arguing:
* that people who are familiar with technology might be more likely to recognize certain keywords than `Community Chat`.
* it shouldn't be an either or, one should be able to do `Community Chat _chat logo_ ( _discord logo_ Discord)` at least in certain places (obviously not in an icon grid).

> We do highlight Community Chat [here](https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md?plain=1#L100) with a link to the Discord server. We also mention it [here](https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md?plain=1#L101), but without a link (as it's linked in the line above).

The problem I had is that I was scanning the left for keywords and not reading the entire contents. I know, I'm bad:

> 🃏 So much to do, and so little time

The relevant section:
https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md#get-buyoff-or-find-open-community-issuesfeatures

Renders as:
![image](https://user-images.githubusercontent.com/2119212/158252792-104bc4a9-ef07-41ff-9d8a-5e887aad4c20.png)

While skimming, I see things that are roughly items that appear in a Table of Contents (ToC/TOC), or things that happen to match patterns my brain already recognizes. The `Community Chat` here was too far into the minutiae for me to spot it. Again, this is more my fault than yours, but it's addressable, as I'm sure there are other people like me.

>> Add a textual item for Community Chat (Discord) to https://community.chocolatey.org/

> Can you clarify what you mean?

Something that:
* can be found using `find` (`cmd`-`f`/`control`-`f`)
* would be visually distinguishable as the words `Community Chat (Discord)` if using one's eyes (but without happening to recognize icons that one doesn't automatically know, i.e. not 

> We talk about that [here](https://github.com/chocolatey/choco/#chat-room) and have it in the TOC at the top too. However, the link is a button - does that not work for you?

Yeah, you do. I'm really not sure how I missed this. This seems to be my biggest blunder. But, note it's `Chat Room` instead of `Community Chat Room` that you use everywhere else. (Not that the extra word would have helped me...)

My best guess is that my eyes jumped to the `!` in [Support Chocolatey**!**](https://github.com/chocolatey/choco/#support-chocolatey) and started scanning from there. I really can't explain it. I'm pretty sure my scan then jumped to:
* [Information](https://github.com/chocolatey/choco/#information) (quickly scanning [Documentation](https://github.com/chocolatey/choco/#documentation) / [Requirements](https://github.com/chocolatey/choco/#requirements) / [License / Credits](https://github.com/chocolatey/choco/#license--credits))
* [Submitting Issues](https://github.com/chocolatey/choco/#submitting-issues)
* [Contributing](https://github.com/chocolatey/choco/#contributing) 
... and then continuing.

Fwiw you shouldn't include punctuation in your headings (Prerequisites:, Build Process:).

> It's not mentioned in the TOC. The Contributing doc is for Contributing to the Chocolatey CLI software. So it talks about how to setup your development environment, commits, code styles etc.

To me, contributing generally includes how to discuss contributions as well as the technical details of how to make commits. After all, you include [Submit Pull Request (PR)](https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md#submit-pull-request-pr).

Hope that's helpful.

**Comment by st3phhays** [comment]
There have been a few PRs that have come out of this to:

1. Add hover text to social media icons in the footer 
2. Add Community Chat into the top Community navigation dropdown. 

After reading this thread, I'm a little unsure if there are still action items to do here. It seems that many different things are being discussed. At this time, if there are more specific changes that need to be made, I new issue should be created with specific actions so that we can track them and implement as needed.
