### ISSUE TITLE
Package Validator not validating URL's

### ISSUE THREAD

**Issue by pauby** [chocolatey/home#144]
### What You Are Seeing?
The Package Validator is failing on the [`webview2-runtime`](https://community.chocolatey.org/packages/webview2-runtime/) package for the [`projectUrl`](https://community.chocolatey.org/packages/webview2-runtime/), even though it is valid _from my side_.

This looks to be related to #60.

### What is Expected?
The projectUrl is not flagged as invalid.

### How Did You Get This To Happen? (Steps to Reproduce)
N/A.

### System Details
N/A

### Output Log
N/A

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/package-validator/-/issues/278) by [Unito](https://www.unito.io)

**Comment by TraGicCode** [comment]
Hey @pauby ,

I own this package and it failed the automated process because of the package validator complaining about the DocsUrl in the nuspec.  Unfortunately, i see nothing wrong with it and i'm pretty much blocked with my package from getting new versions now.

https://community.chocolatey.org/packages/mongodb-compass-isolated/1.31.1

**Comment by Windos** [comment]
Just to flesh out what @TraGicCode reported there, this appears to be impacting all of the MongoDB Compass packages (which reference the same docs URL):

**Package affected**:

* mongodb-compass ([1.31.0+](https://community.chocolatey.org/packages/mongodb-compass/1.31.0))
* mongodb-compass-readonly ([1.31.0+](https://community.chocolatey.org/packages/mongodb-compass-readonly/1.31.0))
* mongodb-compass-isolated ([1.31.0+](https://community.chocolatey.org/packages/mongodb-compass-isolated/1.31.0))

**URLs affected**:

* https://docs.mongodb.com/compass/current/

Checking that URL locally, it loads "fine" but does have a couple of 401 responses while it's loading.

![401 responses](https://user-images.githubusercontent.com/6955786/168560928-3e5482bb-4523-4def-8bcb-397329209163.png)

**Comment by gep13** [comment]
Looks like we have another candidate as well 😢 

* puppet-agent - https://community.chocolatey.org/packages/puppet-agent/7.16.0

This URL is failing to validate correctly:

* https://puppet.com/puppet/puppet-open-source/

**Comment by TheCakeIsNaOH** [comment]
Another package:

URLS:
- https://www.deepl.com/translator
- https://www.deepl.com/en/pro-license?tab=free

Package: 
- https://community.chocolatey.org/packages/deepl/3.5.25837

**Comment by TheCakeIsNaOH** [comment]
And another:

URL: https://www.binance.com/en/terms
Package: https://community.chocolatey.org/packages/binance/1.36.0

**Comment by tunisiano187** [comment]
Still present for this too :
https://community.chocolatey.org/packages/binance/1.41.0
URL: https://www.binance.com/en/terms

**Comment by TheCakeIsNaOH** [comment]
Another package: https://community.chocolatey.org/packages/AdobeAIR/33.1.1.932
Failing URL: https://airsdk.harman.com/runtime

**Comment by TheCakeIsNaOH** [comment]
Another package: https://community.chocolatey.org/packages/deepl/4.0.6052
Failing URLs: https://www.deepl.com/translator and https://www.deepl.com/en/pro-license?tab=free

**Comment by gep13** [comment]
Slack may be hitting the same issue: https://community.chocolatey.org/packages/slack/4.34.115

**Comment by jordigg** [comment]
Have the same problem with Office365 https://community.chocolatey.org/packages/Office365Business/16731.20354
Affected URL: https://www.microsoft.com/en-us/microsoft-365

The package is currently broken for some time now, Microsoft deletes old installer version once a new one is released, so I've been getting comments from angry people for days.

**Comment by flcdrg** [comment]
ProjectUrl for https://community.chocolatey.org/packages/microsoft-teams and https://community.chocolatey.org/packages/microsoft-teams.install is now hitting this.

The URL being flagged is https://www.microsoft.com/en-us/microsoft-teams/group-chat-software which is legit

**Comment by flcdrg** [comment]
https://www.gnu.org/licenses/lgpl-3.0.html getting flagged from https://community.chocolatey.org/packages/mmsstv/1.13.1

**Comment by schlotter** [comment]
Same for https://cdn.statically.io/gh/subsurface/subsurface/master/icons/subsurface-icon.png at https://community.chocolatey.org/packages/subsurface/6.0.5038

**Comment by Schroedingers-Cat** [comment]
This [package version](https://community.chocolatey.org/packages/uhe-satin/1.3.3)'s `DocsUrl` is also affected. The [URL works fine here](https://dl.u-he.com/manuals/plugins/satin/Satin-user-guide.pdf).

**Comment by tunisiano187** [comment]
Same for this [Thebrain.install](https://community.chocolatey.org/packages/thebrain.install/14.0.0)
It was for the Docurl, but even by removing it, it still fails

**Comment by tunisiano187** [comment]
> Another package:
> 
> URLS:
> 
> * https://www.deepl.com/translator
> * https://www.deepl.com/en/pro-license?tab=free
> 
> Package:
> 
> * https://community.chocolatey.org/packages/deepl/3.5.25837

Hello,
I'd say every version of [deepl](https://community.chocolatey.org/packages/deepl) since ... i don't remember ;-)
