### ISSUE TITLE
Update result in configuration deletion

### ISSUE THREAD

**Issue by puschie286** [chocolatey/home#165]
### What You Are Seeing?
"Fork" update by chocolatey result in the deletion of configuration

### What is Expected?
Update process should not delete configurations

### How Did You Get This To Happen? (Steps to Reproduce)
1. Install "Fork" via Chocolatey
2. Start "Fork" and complete the "first time launch process"
3. Wait for new update release ( and dont update by the integrated Fork updater )
4. Update "Fork" via Chocolatey
5. Start "Fork" after update
--> First time launch process is shown again ( which shows that no configuration exist anymore )

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.19044.0
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.19041.1682
* Chocolatey version (Run `choco --version`): 1.1.0

This happend after each update ( of Fork ). Didnt notice any similar behaviour for other packages

**Comment by TheCakeIsNaOH** [comment]
@puschie286 as far as I can tell, this is an issue with the software the package installs, not with Chocolatey itself, or the Community Repository. 

https://github.com/fork-dev/TrackerWin/issues/5
https://community.chocolatey.org/packages/git-fork#comment-4674844981

I'd suggest contacting the package maintainer to see if they have any workarounds, or the upstream software vendor to see if they can fix the installer behavior.

**Comment by puschie286** [comment]
oh, thanks for pointing out
