### ISSUE TITLE
[Chocolatey.org] Profile link broken

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/home#17]
just noticed the "Profile" link on https://chocolatey.org/packages is broken. Instead of my profile it's pointing to "https://chocolatey.org/account/Profiles", which doesn't exist
![image](https://user-images.githubusercontent.com/384747/109376707-4e9bb200-7916-11eb-81bb-d79c9fdcf456.png)

**Comment by gep13** [comment]
@flcdrg I am not able to replicate this problem.  Can I ask that you try logging out of the site, and back in again?

While I am logged in, the Profile link correctly takes me to https://chocolatey.org/profiles/gep13

**Comment by AdmiringWorm** [comment]
@gep13 I noticed the problem happened a couple of times, however I think it was down to caching at the time.
This could be the same thing.

**Comment by flcdrg** [comment]
Working for me today.. a hard computer science problem :-)
