### ISSUE TITLE
Install script fails if the install folder is already present, and doesn't work if not run as admin

### ISSUE THREAD

**Issue by jeiesel** [chocolatey/home#18]
When trying to install chocolatey with this script:
`Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex`
I forgot to use admin grants, and when retrying it prompted me:
'ADVERTENCIA: An existing Chocolatey installation was detected. Installation will not continue.                                        For security reasons, this script will not overwrite existing installations.'
Looking at [Install.ps1](https://chocolatey.org/install.ps1) file, I discovered at 'Test-ChocolateyInstalled' function, that it assumes if '"$env:PROGRAMDATA\chocolatey"' folder exists, chocolatey is installed, but don't. Just removing this folder has fixed my installation and run first script has worked.
Is my first Issue in an opensource project, be kind :)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1063) by [Unito](https://www.unito.io)

**Comment by ferventcoder** [comment]
Howdy! It seems while the messaging may need to be clarified, the behavior is by design and for security reasons.

Perhaps we should drop some notes about why the install won't continue and how folks can correct that?

**Comment by steviecoaster** [comment]
Created https://github.com/chocolatey/docs/issues/146 to track this work.

**Comment by ferventcoder** [comment]
Love that we'd put that in docs as well. I am looking for it in the actual script when it decides not to do something.

**Comment by AdmiringWorm** [comment]
@ferventcoder, I think there *may* need some enhancement as well.

Considering his first run didn't do anything (or shouldn't have at least), then when he ran the script the second time as an admin, he got the message that the install folder existed.

Maybe there is a point to update the install script to rollback any changes if the installation failed?

**Comment by ferventcoder** [comment]
@AdmiringWorm possibly - if it created the folder. I would caution to be very careful on destructive type changes versus just asking the user to go make changes.

**Comment by AdmiringWorm** [comment]
I understand not wanting to do any destructive changes, especially in cases if something other than the install script also made changes.
I meant to only rollback the changes the install script itself did, not anything else though.

Alternatively,
there could perhaps be a prompt when such a failure happens that asks if the user wants to rollback (or delete the install folder and environment variables).
This should obviously only happen in an interactive shell, have `No` as its default and provide a timeout if no answer is given by the user.

**Comment by vexx32** [comment]
The install script itself which handles the pre-checking isn't directly responsible for folders or files created; it pulls the `chocolateyInstall.ps1` script from the Chocolatey package it downloads and runs that directly. That also means it's not exactly simple to just "roll back" any changes that may have been made.

I think either a prompt on failure, or simply a more detailed error/warning on failure is probably the best course of action here, advising the user to nuke the folder and/or env variables if they want to attempt a reinstall.

**Comment by pauby** [comment]
@vexx32 Has this functionality been added? If memory serves me right, the script has been updated since the date of that last comment.

**Comment by vexx32** [comment]
I don't believe the behaviour in this part of the script has been updated yet, no.
