### ISSUE TITLE
See #14 , open the API so Tor users can use choco over tor

### ISSUE THREAD

**Issue by TwoSixtyThreeFiftyFour** [chocolatey/home#182]
See #14 

Let people use Choco over Tor automatically to query the repository and install packages over Tor. Automatically. Not Manually. 

Please this is just a few checkboxes in CloudFlare ... If a targeted malicious adversary wants to tamper with your API, do you really think blocking Tor will stop them? Your threat modeling is kinda weird.

- If you're mitigating script kiddies, hopefully your API is secure against those.
- If you're mitigating skilled adversaries, do you think this will stop them and they'll be like "oh well ... no Tor so  let's top here". Proxies and the likes do not exist...

You're intentionally preventing people who might need updated software more than anyone else from using your app... Why don't you publish a version of your API specifically on a Tor Hidden service? Anyway ... Okay you don't want Tor users to use choco ... fine but admit it and don't say like "just install packages manually". Most terrible excuse ever.

**Comment by pauby** [comment]
We made it clear in [the comment](https://github.com/chocolatey/home/issues/14#issuecomment-1039534281) on the issue as to why we won't be opening this up any further than we have done. I have hidden your response to that question as it doesn't help further that issue and is bordering on abusive.

Just to be clear, there is no such thing as 'just a few checkboxes in CloudFlare' in Enterprise infrastructure.
