### ISSUE TITLE
I searched for the gsmartcontrol package. It wasn't found, even though it exists.

### ISSUE THREAD

**Issue by unforgettableid** [chocolatey/home#184]
### What You Are Seeing?

"Search for 'gsmartcontrol' Returned 0 Packages".

![Screenshot](https://user-images.githubusercontent.com/10241454/189123686-2d03a70c-0b15-48a5-ab7a-aa92d73c68e5.png)

### What is Expected?

I was hoping to see a link to [the GSmartControl package page](https://community.chocolatey.org/packages/gsmartcontrol).

### How Did You Get This To Happen? (Steps to Reproduce)

I went to:  https://community.chocolatey.org/packages?q=gsmartcontrol

**Comment by corbob** [comment]
Duplicate of #8 

Unfortunately there's not much that we can currently do for the situation until some infrastructure changes are completed.

**Comment by corbob** [comment]
Duplicate of #8
