### ISSUE TITLE
Unable to navigate to https://community.chocolatey.org/installChocolatey.cmd

### ISSUE THREAD

**Issue by Allu-Philip** [chocolatey/home#186]
DISPLAY RESULTS
ERROR 404: PAGE NOT FOUND.
You might be here because:
The page you are looking for does not exist anymore.
We moved the page that you are looking for, sorry!
You know how to hack URLs and you're trying to find something.
We just plain suck and messed something up.
Try Searching Again
![BUGGGG](https://user-images.githubusercontent.com/33429916/189475545-310eaee7-50d9-4356-9729-eb2602b4ccfd.jpg)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1167) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
Can I ask what makes you think that there should be a page at that address?

https://community.chocolatey.org/installChocolatey.cmd

Were you linked to there from another location?

**Comment by Allu-Philip** [comment]
Hello Gary,
This link was shown or connected from some other page please check.
Please check this page
Chocolatey Software Docs | Setup / Install
<https://docs.chocolatey.org/en-us/choco/setup#install-using-powershell-from-cmd.exe>
Check this line
"You can also get to this file by going to
https://chocolatey.org/installChocolatey.cmd."
Best Regards
Alex philip

**Comment by gep13** [comment]
@Allu-Philip Thank you for taking the time to report this issue. This should now be corrected.
