### ISSUE TITLE
Where are the terms of use for the website?

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/home#19]
In https://github.com/chocolatey/home/issues/7#issuecomment-776817912, it is stated that "it would be a violation of terms of use" to access Chocolatey.org packages information outside of choco.

However, I cannot find terms of use anywhere on Chocolatey.org. The privacy policy just talks about privacy policy stuff. There is the [legal page on the docs](https://docs.chocolatey.org/en-us/information/legal), but I don't see anything like a terms of use for the website there, just things like licensing for choco, and information regarding the actual packages on the community repository.

If I'm just blind and missed it, just point me in the right direction.

- - -
The reason I am asking, is that there are lots of things currently accessing information about Chocolatey.org packages outside of choco. 

* AU checks if the package version already exists
* [repology](https://repology.org/) check the latest version of pretty much every package. 
* [shields.io](https://shields.io/) has badges with scraped download counts
* Anyone using a Nexus, ProGet, or Artifactory with a proxy repository to Chocolatey.org is getting information about packages outside of choco.

There are probably others (most likely lots of others), but those are the ones I know of. And if accessing information about packages on Chocolatey.org outside of choco is against the TOS, then all of those are then against TOS. So I'd like to read what it actually is.

- - -
I do understand the API is not documented, and that no support will be provided. But a lack of documentation and support is very different from use being prohibited by a TOS.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1125) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
The terms for usage of the site can now be found on https://chocolatey.org/terms

Let us know if you have any questions/concerns.
