### ISSUE TITLE
1st login confirmation email fails to send (w/error)

### ISSUE THREAD

**Issue by dylanh724** [chocolatey/home#190]
### What You Are Seeing?
> There was an issue resending your confirmation token.
![image](https://user-images.githubusercontent.com/8840024/192748374-d6c5706f-1b4f-4900-bbd7-dacd76fab2bd.png)

### What is Expected?
Email confirmation token was sent.0 +

### System Details

* Tried with Chrome
* Tried with Firefox
* Tried with another PC - seems server side.

### Output Log
Nothing useful in f12 console.

**Comment by dylanh724** [comment]
This still happens - not sure who to @ping for this.

**Comment by pauby** [comment]
@dylanh724 Let me pick this up internally.

**Comment by pauby** [comment]
@dylanh724 Can you join the [Discord server](https://ch0.co/community) and DM me (pauby) so I can grab some info from you privately?

**Comment by pauby** [comment]
To update this issue before I close it, the solution was that there was no account registered.

**Comment by dylanh724** [comment]
To clarify, I tried to register multiple times and it said I had an account, already. When I went to login, it would say I first news to activate the account via an email code. When I enter my email here, I got the error.
