### ISSUE TITLE
Package verifier failure message has dead link to verifier wiki

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/home#20]
![verifier](https://user-images.githubusercontent.com/38865330/109977177-2cad8100-7cc2-11eb-9ce3-fff646babda7.png)

The highlighted link points to https://github.com/chocolatey/package-verifier/wiki, while it should instead point to https://docs.chocolatey.org/en-us/community-repository/moderation/package-verifier

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/chocolatey-software/community.chocolatey.org/-/issues/1062) by [Unito](https://www.unito.io/learn-more)

**Comment by gep13** [comment]
@TheCakeIsNaOH thanks for raising this.  I am in the middle of making some changes to the Community Repository, when that work is completed, I should be able to address this.  Thanks

**Comment by gep13** [comment]
@TheCakeIsNaOH I have pushed out a new version of the site that addresses this issue, and any package moderation emails that are sent out going forward, should include the new email text.  Thanks for pointing this out!
