### ISSUE TITLE
Shims do not behave like the raw executable (file output delayed)

### ISSUE THREAD

**Issue by mueslo** [chocolatey/home#211]
While this is an issue I encountered with a specific package, I think it likely points to a deeper deficiency of chocolatey shims / shimgen.

I also detailed it outside of the chocolatey sphere already quite a while ago [here](https://github.com/jupyter/nbconvert/issues/1619) and in the [discussions of chocolatey-packages here](https://github.com/chocolatey-community/chocolatey-packages/discussions/2036) at the request of the package maintainers, but received no response so far.

### What You Are Seeing?

I have Inkscape installed via chocolatey. This installs Inkscape's `inkscape.exe` as a shim (https://github.com/chocolatey-community/chocolatey-packages/pull/1347), and makes this shim available system-wide via `PATH`. 

I am using a Python script which calls `inkscape` to convert an svg to pdf (the details are not super important, but it is `jupyter nbconvert`, in particular [this part](https://github.com/jupyter/nbconvert/blob/29169a1372d8904863ce01b6f5a3acaa11c3af4a/nbconvert/preprocessors/svg2pdf.py#L144-L153)). However, this results in an extremely nondescript error. With some debugging I had found that the issue is that the output file supposed to be generated by `inkscape` does not exist at a time when `inkscape` already finished execution. However, manually running the same command works fine to generate the desired output. This suggests that `inkscape`, which resolves to the shimmed `inkscape.exe`, does not behave the same as the true `inkscape.exe` and terminates before it actually writes the output.

To confirm this, I tried running the Python conversion script using the following:
1) with a shimmed `inkscape.exe` and an explicit delay (1s) in the Python script
-> works, no error
2) with true `inkscape.exe` included in `PATH` with precedence over chocolatey shims
-> works, no error
3) with `inkscape.com` included in `PATH` with precedence over chocolatey shims
-> works, no error

Further, the `inkscape.exe` shim generation does NOT use the `-UseStart` option which would explicitly result in this behaviour. You can convince yourself of that fact in [chocolateyInstall.ps1](https://community.chocolatey.org/packages/InkScape#files):

```powershell
if ($installLocation) {
  Install-BinFile 'inkscape' $installLocation\bin\inkscape.exe
  Write-Host "$packageName installed to '$installLocation'"
}
```

### What is Expected?

Shims behave like the executable they are shimming or are not used.

While you could imagine that this could be result of some buffer flushing trickiness as a result of shimming, it can't be the result of an missing OS-level fsync, since once the previous program terminates the output file must be accessible to the kernel (even if not physically written to disk yet).

### How Did You Get This To Happen? (Steps to Reproduce)

1. Install Inkscape with Chocolatey
2. Try to convert an Jupyter notebook with `nbconvert` (or use the file output of an Inkscape command line call immediately after it terminates).

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.17763.0
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.17763.2931
* Chocolatey version (Run `choco --version`): 1.1.0

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/shimgen/-/issues/40) by [Unito](https://www.unito.io)
┆Link To Issue: https://gitlab.com/chocolatey/collaborators/shimgen/-/issues/40

**Comment by mueslo** [comment]
I just read about the `--shimgen-log` command, and it seems like the Inkscape shims are generated as if `-UseStart` was on. Why?

```
> inkscape.EXE --export-filename="C:\Users\username\AppData\Local\Temp\tmpa2zxa900\figure.pdf" "C:\Users\username\AppData\Local\Temp\tmpa2zxa900\figure.svg" --shimgen-log
[shim]: Set up Shim to run with the following parameters:
  path to executable: c:\program files\inkscape\bin\inkscape.exe
  working directory: C:\ProgramData\chocolatey\bin
  is gui? True
  wait for exit? False
  command (optional):
[...]
```

**Comment by brogers5** [comment]
This sounds like a situation where you may want to override the generated GUI shim's default behavior with the `--shimgen-waitforexit` switch. Unlike a command-line shim, a GUI shim would normally terminate after starting the shimmed executable in order to avoid blocking the console session.

Related: #137

**Comment by mueslo** [comment]
I know of this possibility. However, the shim should behave as the shimmed executable. It is not reasonable to account for broken shims in other programs via workarounds.

**Comment by pauby** [comment]
@mueslo Can you update your original issue post above with exact steps to reproduce? The steps you have provided are not clear and open to interpretation.

**Comment by mueslo** [comment]
Which part is not clear or open to interpretation for you?

**Comment by pauby** [comment]
The section 'How Did You Get This To Happen? (Steps to Reproduce)'.

**Comment by mueslo** [comment]
You are paraphrasing your previous statement/request. I am sorry but I don't know how I can be any clearer if you don't tell me what part you deem unclear and why.

**Comment by pauby** [comment]
>1.  Install Inkscape with Chocolatey

That makes sense. What we;re looking for here is 'choco install inkscape'. That way we know _exactly_ what command you are running, if you are adding any options etc.

> 2. Try to convert an Jupyter notebook with nbconvert (or use the file output of an Inkscape command line call immediately after it terminates).

What does that mean? What command are you running? Where will we get a sample Jupyter notebook? What _exactly_ are you doing in this step?

The goal of the steps to reproduce is so that we can reproduce the issue you are seeing. To do that we need to follow the same steps that you followed _exactly_ to cause the problem _exactly_ as you get it. We don't want to interpret what your steps are or guess what they are because then we are wasting our time and yours. We might not be able to reproduce it and it's because we're not using the same Jupyter notebook, or the same options or something else.

So the steps to reproduce are the _exact steps you followed to cause this problem_.

**Comment by mueslo** [comment]
> use the file output of an Inkscape command line call immediately after it terminates

```bat
@echo off
if not exist input.svg curl https://upload.wikimedia.org/wikipedia/commons/8/8a/BlankMap-World-v2.svg -o input.svg
del output.pdf
inkscape --export-filename="output.pdf" "input.svg"
if not exist output.pdf echo output.pdf does NOT exist after termination
timeout /t 5 /nobreak > NUL
if exist output.pdf echo exists after 5s delay
pause
```

**Comment by pauby** [comment]
Can you back up to your [original issue post](https://github.com/chocolatey/home/issues/211#issue-1431952303) and update the steps to reproduce with this information? If the Jupyter notebook is not required, then remove it?
