### ISSUE TITLE
Nexus gets 403 from chocolatey.org

### ISSUE THREAD

**Issue by ImNtReal** [chocolatey/home#233]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

From a linux server in my environment, chocolatey.org is returning 403 forbidden when it attempts to retrieve package metadata via https://chocolatey.org/api/v2. I also get a 403 when trying that URL with wget on the same server.

From my workstation on the same network, I get an XML document.

### What is Expected?

I expect the metadata about the package to be returned with HTTP 400.

### How Did You Get This To Happen?

1. Set up and run Nexus as a Chocolatey proxy for years.
2. One day discover that package metadata isn't updating.
3. See 403 errors in Nexus log while trying to communicate with chocolatey.org.

### System Details

* Operating System: RHEL 8
* Windows PowerShell version: N/A
* Chocolatey CLI Version: N/A
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: N/A
* Terminal/Emulator: xterm-256color

### Installed Packages

```bash
N/A
```

### Output Log

```bash
2022-12-06 13:46:41,876-0500 WARN  [qtp1451928026-527]  *UNKNOWN com.sonatype.nexus.repository.nuget.internal.NugetFeedFetcher - Status code 403 contacting https://chocolatey.org/api/v2/Search?$skip=0&$top=80&searchTerm='chocolatey'&targetFramework=''&$filter=IsLatestVersion&includePrerelease=false
```

### Additional Context

It's possible that something has caused me to get blocked on purpose, but I'm not sure what that would be. All caching options for the Chocolatey proxy are set to 24 hours.

**Comment by TheCakeIsNaOH** [comment]
Give this a read through: https://docs.chocolatey.org/en-us/troubleshooting#im-getting-a-403-unauthorized-issue-when-attempting-to-use-the-community-package-repository

**Comment by ImNtReal** [comment]
I forgot about the blocked IP form. Also, I just realized that my PC isn't a good test case since our Windows machines go through a proxy that Linux machines don't. If I am being blocked intentionally, I'll close this out.

**Comment by pauby** [comment]
@ImNtReal Can you close this if it's no longer an issue?

**Comment by pauby** [comment]
I'm going to go ahead and close this, but we can reopen it if necessary.
