### ISSUE TITLE
Toggle Arrows Appear Expanded but No Info Shown on Package Page (moderators/admin)

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/home#24]
When logged in as a moderator/admin, and on an approved package page, some of the toggle dropdown arrows for the sections appear to be expanded, however they are not. These arrows should be collapsed like the rest of the sections on an approved package page.

![image](https://user-images.githubusercontent.com/42750725/111341316-66c63d80-8647-11eb-933b-2dce2a9d8688.jpg)

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/chocolatey-software/community.chocolatey.org/-/issues/1066) by [Unito](https://www.unito.io/learn-more)

**Comment by gep13** [comment]
@mkevenaar FYI...
