### ISSUE TITLE
Some Package Icons Not Visible on Dark Mode

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/home#25]
While in dark mode on the chocolatey packages page, some of the package icons are hard to see. There should perhaps be some kind of light background on each package image to improve accessibility of these icons while in dark mode.

![Screen Shot 2021-03-16 at 11 05 54 AM](https://user-images.githubusercontent.com/42750725/111341887-efdd7480-8647-11eb-8bc7-56cc3b5e0616.png)

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/chocolatey-software/community.chocolatey.org/-/issues/1065) by [Unito](https://www.unito.io/learn-more)

**Comment by gep13** [comment]
Going forward, this is going to look like the following:

| light | dark |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/1271146/111435351-9719e480-86f8-11eb-8284-521f02508ca8.png) | ![image](https://user-images.githubusercontent.com/1271146/111435319-8cf7e600-86f8-11eb-8bf4-21d3658af9f1.png) |
