### ISSUE TITLE
Space at beginning of generated Config-File 

### ISSUE THREAD

**Issue by marvUta** [chocolatey/home#256]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

The generated config files are starting with a space which fails the validation.

![grafik](https://github.com/chocolatey/home/assets/9527130/4006809b-a35e-4ca0-a408-2aa2c96cad6f)

Unexpected XML declaration. The XML declaration must be the first node in the document. No spaces are allowed before it. Line 1, position 4. (Translated by GoogleTranslator)

![grafik](https://github.com/chocolatey/home/assets/9527130/976fcbb3-5d12-4409-98e9-5c903f24799e)
Space at the beginning which occurs the error while validating.

### What is Expected?

An generated XML-Config file which gets properly validated without the space at the beginning.

### How Did You Get This To Happen?

1. Search any package on https://community.chocolatey.org/packages
2. Select the package to add it to the builder
3. Generate Script
4. Save as .config File

### System Details

* Operating System: WIN11 (22621.1702)
* Windows PowerShell version:  Microsoft.PowerShell         7.3.4
* Chocolatey CLI Version: Chocolatey v1.4.0
* Chocolatey Licensed Extension version: -
* Chocolatey License type: -
* Terminal/Emulator: -

### Installed Packages

```bash
Not package related issue.
```

### Output Log

```bash
chocolatey.infrastructure.app.configuration.PackagesConfigFileSettings:
 Unerwartete XML-Deklaration. Die XML-Deklaration muss der erste Knoten im Dokument sein. Davor sind keine Leerzeichen zulässig. Zeile 1, Position 4.

Unexpected XML declaration. The XML declaration must be the first node in the document. No spaces are allowed before it. Line 1, position 4. (Translated by GoogleTranslator)
```

### Additional Context

As workaround, just remove the space at the beginning and the config file is interpreted correctly.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1225) by [Unito](https://www.unito.io)

**Comment by pauby** [comment]
I just tried this and confirmed it's an issue. 

@st3phhays can you have a look at this?

**Comment by st3phhays** [comment]
This fix has been released and all should be good now on Script Builder.
