### ISSUE TITLE
Give shimming/Shimgen arguments or features to users

### ISSUE THREAD

**Issue by fabiorzfreitas** [chocolatey/home#278]
### Checklist
* [x] I have verified this is the correct repository for opening this issue.
* [x] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.
There were a few packages I installed for which I expected shims. Instead, I had to manually use `Shimgen.exe` for them.

### Describe The Solution. Why is it needed?
Shim generation is handled by the package maintainer with `Install-BinFile`. Sometimes a maintainer chooses not to shim the executable. Sometimes a user will miss the feature.

As for me, I had to manually shim `firefox-dev`, `googlechrome` and `regcool.install`. Whether my preference should be default or not, it's not a worthy debate.

Instead, I'd like to suggest a `Shim` feature or argument. Perhaps either of those can simply check `chocolateyInstall.ps1` for `Install-BinFile` and add it if necessary before running it.

Another approach would be to have the user to pass `Shimgen.exe` arguments just like `--params`:

`--shim="'-o=PATH -p=PATH -i=PATH --gui'"`

I realize this might not help when installing new packages, but it could be very useful for redeploying or for a `choco upgrade -f` right after inspecting the installation path.

### Additional Context
Just for a quick personal example on why I needed the Shims: I wanted to run `chrome.exe URL1 URL2 URL3...`. This would be done via Win+R Run, but a little batch script was way more efficient for what I wanted to do.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/shimgen/-/issues/45) by [Unito](https://www.unito.io)

**Comment by pauby** [comment]
> Shim generation is handled by the package maintainer with Install-BinFile. Sometimes a maintainer chooses not to shim the executable. Sometimes a user will miss the feature.

Shim generation is handled automatically by Chocolatey CLI when an executable file is dropped into the package folder (`$env:ChocolateyINstall\lib\<PACKAGENAME>`). Package maintainers can also create them.

> As for me, I had to manually shim firefox-dev, googlechrome and regcool.install. Whether my preference should be default or not, it's not a worthy debate.

I disagree. I believe it is worthy of debate. 

Google Chrome, Firefox Dev, and RegCool all install in their associated folders outside the Chocolatey package folder. Chocolatey CLI will therefore not automatically shim them. In the case of Google Chrome, it is available on the PATH already (as `chrome.exe`) and assuming Firefox Dev is the same as Firefox, it will be available on the PATH as `firefox.exe`. 

If you install a Chocolatey package that runs an installer to install the software, then if it is intended to be used on the command line, the software author will add it to the PATH through their installer. If that doesn't happen, then the package maintainer may work around this by doing it manually in the package.

If the software does not add its executables to the PATH, then there are options already:

1. Contact the software author and ask them to add their end installation location to the PATH.
2. Contact the package maintainer and ask them to add a shim to the package for the software to work around the above issue.
3. Add the installation location to the PATH manually.

Shimgen is not intended to be run by the end-user for creating shims. If that is needed, then there is an issue with the package or software that needs to be addressed separately.

**Comment by fabiorzfreitas** [comment]
> Shim generation is handled automatically by Chocolatey CLI when an executable file is dropped into the package folder ($env:ChocolateyINstall\lib\<PACKAGENAME>). Package maintainers can also create them.

Well, I can't dispute that. I figured single-file cli executables would be installed in a way to be automatically handled. Still, I inspected a handful of different non-cli packages and found out that all of them had `Install-BinFile` somewhere on `chocolateyInstall.ps1`.

> In the case of Google Chrome, it is available on the PATH already (as `chrome.exe`) and assuming Firefox Dev is the same as Firefox, it will be available on the PATH as `firefox.exe`.

In my current experience, which is a fresh installation of Windows 11 on a wiped SSD, using a single account, which has access to admin rights, every installed packaged was done calling their own instance of `choco.exe` (i.e., no multi-package installs), although it may be meaningful that every call was to `choco.exe upgrade <PACKAGE> -y` instead of `choco.exe install`. I don't have the script anymore, but it consisted of a bunch of single-liners containing said pattern (and a few `--params` for some packages).

I probably redirected the whole thing to a text file to find out about any errors and reinstall as needed.

Firefox and Chrome didn't have errors, as expected

**Comment by AdmiringWorm** [comment]
@fabiorzfreitas As an alternative to what you are currently doing, and what you are requesting.

A user already technically has the ability to run and create shims automatically as part of installing packages, even if the maintainer has decided not to do it as part of the package installation. This does require a bit of legwork up front before it can be used, though.

We have something called hook scripts, as well as `.hook` packages that can achieve this.

The way to use this is by creating a script in `%ChocolateyInstall%\hooks`. The name of this script depends on when you want the script to run, for what package it should run on (or all packages).

Taking the `firefox-dev` package as an example, if you want to ensure that a shim is created after the installation of this package, you'd create the file with the name `post-install-firefox-dev.ps1`.

The content of this script can vary a bit, but it would do something similar to:

1. Get the installation path of the software (`Get-AppInstallLocation` from the `chocolatey-core.extension` can be used in some circumstances here).
2. Call `Install-BinFile` with the path, arguments, etc. that you want.

If going down this path, though, I would also suggest creating a similar file for uninstall (i.e. `pre-uninstall-firefox-dev.ps1`) to remove the shim automatically.

If wanted, multiple such scripts can be packaged up in a package that ends with `.hook` and is hosted internally that you install before any other packages.

The documentation for this is available here: https://docs.chocolatey.org/en-us/features/hook

**Comment by fabiorzfreitas** [comment]
@AdmiringWorm that indeed seems to be more elegant and conforming to Chocolatey's syntax. But if it would require all of this work for each package, I'm not sure it's the best solution.

This would be different if I could create a template `.hook` and attach it to a `choco install` switch (perhaps passing a path to the hook file itself), I could try to work on that. I could either parse `chocolateyInstall.ps1` to look for `Install-BinFile`, or, even better, simply check the default Shim directory. I don't even understand PowerShell (yet), but I could always try to come up with a solution using your methods, which would be more versatile and compatible.

As it is, at least for now, I think I'm better with my one-liners, e.g.:

```
"C:\ProgramData\chocolatey\tools\shimgen.exe" -o="C:\ProgramData\chocolatey\bin\firefox.exe" -p="C:\Program Files\Firefox Developer Edition\firefox.exe" -i="C:\Program Files\Firefox Developer Edition\firefox.exe" --gui
```
