### ISSUE TITLE
Typo fix on chocolatey.org/courses/

### ISSUE THREAD

**Issue by funkyfisch** [chocolatey/home#28]
Hello there! I wanted to submit a typo fix, but I realized the course pages are not part of the actual docs. Is it possible to do so for that part of the webpage, or is it only developed internally?

FYI, the typo in question is in here https://chocolatey.org/courses/getting-started/requirements
![image](https://user-images.githubusercontent.com/4956573/112007066-9b913380-8b24-11eb-88a5-cd09e550c163.png)

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/chocolatey-software/community.chocolatey.org/-/issues/1071) by [Unito](https://www.unito.io/learn-more)

**Comment by gep13** [comment]
@funkyfisch thanks for bringing this to our attention.  You are correct, the source code for the core portion of the Chocolatey website is contained within a private repository, so you will not be able to submit a PR to address the problem.  All pages under docs.chocolatey.org can be submitted to.

I have moved your issue into the `chocolatey/home` repository, as this is the correct place for any closed source portions of Chocolatey.

**Comment by gep13** [comment]
@funkyfisch I have just pushed out a new version of the site that corrects this typo.  Thanks again for reporting this.  Let us know if you find anything else that isn't quite right.
