### ISSUE TITLE
Packages fail verifier because unzipping times out

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/home#289]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

New packages fail Verifier because the unzipping times out.

### What is Expected?

Unzip should not timeout

### How Did You Get This To Happen?

Submit package that requires unzipping

### System Details

-

### Installed Packages

```bash
-
```

### Output Log

```bash
-
```

**Comment by flcdrg** [comment]
https://community.chocolatey.org/packages/waifu2x-extension-gui/3.108.1
https://gist.github.com/choco-bot/68e4304493470b4c613e1856529aef7c#file-install-txt-L503

**Comment by flcdrg** [comment]
Actually it is 1.7 GB, so may be it will take a while

**Comment by flcdrg** [comment]
I have packages hitting the unzip problem (retrying one as we speak). Realised I confused that with this one

**Comment by Windos** [comment]
> @Windos is this not related to the checksum timeout issue?

It may well be the same root cause. The testing box isn't resource constrained, so I'm at a loss as to why unzip and checksum would be struggling so much.

Planning on a little investigation time next week.

**Comment by Windos** [comment]
Just to ensure the comment chain on this issue is complete, after some investigation and changes to the virtual environment, both this unzip issue and the checksum issue appears to have been resolved and packages that were affected are now going through package verification successfully.
