### ISSUE TITLE
Package page shows incorrect content

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/home#29]
When looking at the scripts available for the [Google Chrome](https://chocolatey.org/packages/GoogleChrome#files) package I noticed that the shown helper.ps1 script do not match the content that is in the package file.

it seems to have removed two characters from in the display, which causes most of the file to look like it is a string.

The line being shown on chocolatey.org is:

```ps
if ((Get-ItemProperty $_.pspath).ap -match 'arch_x86) { return $true }
```

but the actual line in the package file looks like this:

```ps
if ((Get-ItemProperty $_.pspath).ap -match 'arch_x86$') { return $true }
```

*notice the missing `*` and the missing single quote `'`, I assume this combination of characters have caused the render to remove the characters.

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/chocolatey-software/community.chocolatey.org/-/issues/1073) by [Unito](https://www.unito.io/learn-more)

**Comment by gep13** [comment]
@designxsteph would you be able to take a look this? Thanks!

**Comment by gep13** [comment]
@AdmiringWorm thanks for raising this. I have just pushed out a new version of the site where this has been addressed.

**Comment by AdmiringWorm** [comment]
@gep13 awesome. I can confirm that it now shows up as it should :smile:
