### ISSUE TITLE
IP Blocking of mutual customers using Chocolatey via JFrog Artifactory

### ISSUE THREAD

**Issue by adam-browning** [chocolatey/home#294]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Hello 
My name is Adam and I'm a Product Manager [JFrog](https://github.com/jfrog)
I am reaching out via this issue since we have been waiting for more the 3 days for a response from one of your representatives https://chocolatey.zendesk.com/hc/en-us/requests/21012

We recently discovered that our mutual customers are being blocked from accessing [](https://community.chocolatey.org/) when requesting from several of our SaaS IPs.

We understand that measures of this type usually occur due to some sort of abusive behavior originating from customers on our end. We are actively working to mitigate the issue and we would like to collaborate together to re-enabled and remove the IP block currently in place.

We are looking forward to working together and I apologize for contacting you via this method.
Thanks in advance,
Adam

### What is Expected?

Please respond to our request

### How Did You Get This To Happen?

NA

### System Details

NA

### Installed Packages

```bash
NA
```

### Output Log

```bash
NA
```

### Additional Context

NA

**Comment by Windos** [comment]
Hi @adam-browning, apologies for the delay responding to your ticket. You should have received an update to it ~16 minutes ago.

**Comment by adam-browning** [comment]
Thank you @Windos 
Much appreciated!
