### ISSUE TITLE
Sales contact page is broken

### ISSUE THREAD

**Issue by jimsansevero** [chocolatey/home#304]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

The page https://chocolatey.org/contact/sales says to "provide the information below" but does not return a form to enter data. 

### What is Expected?

I would expect to get a form that I can use to contact sales

### How Did You Get This To Happen?

https://chocolatey.org/contact/sales

### System Details

N/A

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

**Comment by pauby** [comment]
The page looks as it should for me. Can you provide screenshots of what is broken and what you are seeing?

**Comment by gep13** [comment]
@jimsansevero I can confirm that this is also working for me:

<img width="1514" alt="image" src="https://github.com/chocolatey/home/assets/1271146/dc11e2f6-69a2-482c-aaf6-4ca67b646772">

Is it possible that you have some browsers plugins running that are preventing the loading of certain elements onto the page?  For example, the form that we are using is loaded via an iframe element onto the page.

**Comment by jimsansevero** [comment]
Thank you for the response. There is definitely something going on from my work machine. I'm not sure if it is an add-in, security policy, or proxy/firewall issue. I do see an error opening this page: https://form.jotform.com/jsform/210734668874164
If I try to go to it manually, I get "This site can’t be reached The webpage at https://form.jotform.com/jsform/210734668874164 might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED". I would assume that if it's not working for my company, there are other companies that can't get to it.

**Comment by pauby** [comment]
> I would assume that if it's not working for my company, there are other companies that can't get to it.

We've had no other reports of issues on this page.

> ...I was able to get to it from my personal machine.

I'll go ahead and close this, but we can always reopen it again in the future.
