### ISSUE TITLE
Community Search no longer on community packages pages

### ISSUE THREAD

**Issue by bondo01** [chocolatey/home#309]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

The package search box is missing from the community package web page.

### What is Expected?

a search box that performs a search for packages that match the user's input for a package name should be at the top of the page

### How Did You Get This To Happen?

1. input community.chocolately.org/packages in web browser address bar.
2. scroll up and down page for search box. None found.
3. ![Screenshot 2024-03-27 091124](https://github.com/chocolatey/home/assets/2029669/b190dd5f-8d0f-440f-a53d-93eebdec86eb)

### System Details

* Operating System: Windows 11
* Windows PowerShell version: 7.4
* Chocolatey CLI Version: N/A
* Chocolatey Licensed Extension version: Free
* Chocolatey License type: Free
* Terminal/Emulator: N/A

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

### Additional Context

N/A

**Comment by gep13** [comment]
This looks like a local browser cache issue.

Can you try clearing the browser cache, and try re-loading the page?

**Comment by bondo01** [comment]
Interesting... New computer, new browser...First time accessing Chocolatey.org website with this setup...so Chocolatey puts cookies and prefetched data on all the browsers installed on a PC if Chocolatey is installed on it. How does it do that? So does that mean if I install a new browser on this same system, all the chocolatey web contents would be downloaded to the new browser?

**Comment by gep13** [comment]
> @bondo01 said...
so Chocolatey puts cookies and prefetched data on all the browsers installed on a PC if Chocolatey is installed on it.

Simply put... No.  This is not happening.  Chocolatey CLI does nothing to interact with the browser on an installed machine.

Can you confirm if clearing the browser cache did work, and the search box was restored?
