### ISSUE TITLE
Package page extremely laggy/missing CSS

### ISSUE THREAD

**Issue by Reterino** [chocolatey/home#315]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Going to the Zoom Package page (https://community.chocolatey.org/packages/zoom) is extremely slow to load and then loads with broken CSS/scripts. Confirmed with a few other people that it occurs on this page for them too.

### What is Expected?

Page should load as normal with other pages

### How Did You Get This To Happen?

1. Opened browser
2. Navigated to Chocolatey packages page
3. Search for zoom
4. Click on Zoom Client

Or
1. Go to https://community.chocolatey.org/packages/zoom

### System Details

* Operating System: Windows 11
* Windows PowerShell version: N/A
* Chocolatey CLI Version: N/A
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: N/A
* Terminal/Emulator: N/A

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1273) by [Unito](https://www.unito.io)

**Comment by Reterino** [comment]
Hey @gep13 

The package maintainer for Zoom is also unable to update the package using his normal automatic pipeline (@mikecole), so the package is stuck pretty far out of date.

Do you know if there's a way to clean up old versions (with permission of the package maintainer) from your end to resolve this?

**Comment by corbob** [comment]
To echo what @gep13 already said: Thank you for raising this issue @Reterino. @mikecole should be able to access the zoom package page now.

**Comment by mcolebiltd** [comment]
I can, yes. The page seems to load quickly now. I assume there is no need to delist older versions now?

**Comment by mikecole** [comment]
I can, yes. The page seems to load quickly now. I assume there is no need to delist older versions now?

**Comment by corbob** [comment]
> I assume there is no need to delist older versions now?

That's correct. I would suggest leaving older versions unless there's a reason to delist them.
