### ISSUE TITLE
The login is broken

### ISSUE THREAD

**Issue by tarunbatta** [chocolatey/home#321]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

<img width="761" alt="image" src="https://github.com/chocolatey/home/assets/1251794/b7631af2-4762-4d37-b42f-e309a1f276ec">

### What is Expected?

N/A

### How Did You Get This To Happen?

N/A

### System Details

* Operating System:
* Windows PowerShell version:
* Chocolatey CLI Version:
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

### Additional Context

N/A

**Comment by pauby** [comment]
Its not clear what this issue is. That's one of the reasons we ask for steps to reproduce it.
