### ISSUE TITLE
There was an issue resending your confirmation token

### ISSUE THREAD

**Issue by tarunbatta** [chocolatey/home#322]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

I am facing an issue where after creating an account, I was unable to log in. Later it asked me to to confirm my account. Since I had not received the confirmation email, I clicked on "Lost your confirmation email". From the resend confirmation page, I am getting the following error, "There was an issue resending your confirmation token". Any ideas what could be the issue and how to resolve it?

### What is Expected?

N/A

### How Did You Get This To Happen?

N/A

### System Details

* Operating System:
* Windows PowerShell version:
* Chocolatey CLI Version:
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

**Comment by vexx32** [comment]
@tarunbatta We're looking into what we can on our side as to logs on the backend and such; can you tell me what browser and OS you're using, as well as any extensions that mess with javascript in some way (noscript, ghostery, scriptmonkey, etc)? I'm currently unable to reproduce this issue.

Also, have you tried to resend the confirmation email since the initial incident?

**Comment by vexx32** [comment]
I spoke with our Ops folks and there doesn't seem to be anything unusual in the stored account information or logs that would explain why this is happening.

As a one-off we might try deleting the account and having you re-register it to see if that resolves the issue for you. If you like us to give that a go, please let us know.
