### ISSUE TITLE
API cache is not being removed when a package is approved

### ISSUE THREAD

**Issue by Diazole** [chocolatey/home#328]
### Checklist
* [x] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
* [x] I have verified this is the correct repository for opening this issue.
* [x] I have verified no other issues exist related to my problem.
* [x] I have verified this is not an issue for a specific package.
* [x] I have verified this issue is not security related.
* [x] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?
The chocolatey API cache is not cleared upon package approval for queries that contain unencoded quotes. The choco CLI makes requests to the API using unencoded quotes which is resulting in stale versions being returned until the cache clears after a set period of time.

### What is Expected?
Queries that contain unencoded quotes should be removed from the API cache upon package approval.

### How Did You Get This To Happen?
Querying with `%27googlechrome%27` returns 127.0.6533.120 and `'googlechrome'` returns 127.0.6533.100

With encoded quotes:

```
$ curl --silent 'https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20%27googlechrome%27)%20and%20IsLatestVersion&semVerLevel=2.0.0' | grep \<d:Version\>
      <d:Version>127.0.6533.120</d:Version>
```

Without encoding quotes (what the CLI does):

```
$ curl --silent 'https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20'\'googlechrome\'')%20and%20IsLatestVersion&semVerLevel=2.0.0' | grep \<d:Version\>
      <d:Version>127.0.6533.100</d:Version>
```

### System Details
* Operating System: Windows 10
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 2.3.0
* Chocolatey Licensed Extension version: Chocolatey v2.3.0 Business
* Chocolatey License type: Business
* Terminal/Emulator: Terminal

### Installed Packages
```bash
N/A
```

### Output Log
```bash
N/A
```

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1288) by [Unito](https://www.unito.io)

**Comment by Diazole** [comment]
The vscode package was updated yesterday to version 1.92.2 but the choco cli only sees version 1.92.1 due to this caching issue.

```
choco search vscode --source 'https://community.chocolatey.org/api/v2' --exact
Chocolatey v2.3.0 Business
vscode 1.92.1 [Approved]
```

With encoded quotes:
```
$ curl --silent 'https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20%27vscode%27)%20and%20IsLatestVersion&semVerLevel=2.0.0' | grep \<d:Version\>
      <d:Version>1.92.2</d:Version>
```

Without encoding quotes (what the CLI does):
```
$ curl --silent 'https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20'\'vscode\'')%20and%20IsLatestVersion&semVerLevel=2.0.0' | grep \<d:Version\>
      <d:Version>1.92.1</d:Version>
```

**Comment by gep13** [comment]
@Diazole thank you for raising this issue.  We are working on a solution, and I will report back here once I have more information.

**Comment by Diazole** [comment]
@gep13 This was closed as completed but it still looks like an issue?

```
choco search vscode --source 'https://community.chocolatey.org/api/v2' --exact
Chocolatey v2.3.0 Business
vscode 1.92.2 [Approved]
```

```
$ curl --silent 'https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20%27vscode%27)%20and%20IsLatestVersion&semVerLevel=2.0.0' | grep \<d:Version\>
      <d:Version>1.93.0</d:Version>
```

```
$ curl --silent 'https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20'\'vscode\'')%20and%20IsLatestVersion&semVerLevel=2.0.0' | grep \<d:Version\>
      <d:Version>1.92.2</d:Version>
```

**Comment by gep13** [comment]
> @Diazole said...
This was closed as completed but it still looks like an issue?

To be clear here, this is is closed as `4 - Done`, but not `5 - Released`.  The difference here being that we have finished the code changes to make this happen, however, the changes have not been deployed yet, which is why you aren't seeing any difference.
