### ISSUE TITLE
Authentication expiration / too short sign out time

### ISSUE THREAD

**Issue by wolfthegreat** [chocolatey/home#330]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

I'm getting logget out from community.chocolatey.org in about a week after sign in, which is very annoing.

### Describe The Solution. Why is it needed?

Change the cookie's .ChocolateyGalleryAuthentication Expires/Max-Age from Session to 1 year.

**Comment by pauby** [comment]
The cookie is set to expire for security reasons. This isn't something we will change.

Using a password manager linked to your browser will make it easier, and be less annoying for you, to log in.
