### ISSUE TITLE
Community repository - Review comments and files missing formatting

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/home#41]
On all packages, the review comments and files are all missing formatting.

Using Firefox 87
Not affected by switching light/dark mode.

This is the package I am using: https://community.chocolatey.org/packages/nextcloud-client/3.2.0-rc2

# Missing formatting:
![image](https://user-images.githubusercontent.com/38865330/113176095-bdb83f00-9211-11eb-9a0f-63f0ad91fe26.png)
![image](https://user-images.githubusercontent.com/38865330/113176133-c6107a00-9211-11eb-9527-782f11d21cf2.png)
![image](https://user-images.githubusercontent.com/38865330/113176152-cc065b00-9211-11eb-8bd5-031e0c294e4b.png)

# This is what I am expecting it to look like
Captured on chromium 87

![image](https://user-images.githubusercontent.com/38865330/113176362-fe17bd00-9211-11eb-863e-1ed0c463bc72.png)
![image](https://user-images.githubusercontent.com/38865330/113176382-066ff800-9212-11eb-9db6-cbdbadfb694b.png)

**Comment by AdmiringWorm** [comment]
You may have an addin in firefox that prevents the formatting of the file.

I checked in firefox both on Linux and windows, and it doesn't seem to be anything firefox specific that prevents it.
To make sure, you should probably try opening the page in a private session which usually disables addins and see if the formatting shows up then.

**Comment by AdmiringWorm** [comment]
It could be a configuration setting that is enabled/disabled when running in normal mode and the opposite in private mode, but I'm leaning more towards an add-on.
One that maybe didn't behave as it should, gets loaded differently, or was just missed when disabling the add-ons.
That is just my guess, though.

**Comment by gep13** [comment]
@TheCakeIsNaOH am I right in saying that this can be closed?

**Comment by TheCakeIsNaOH** [comment]
I think so.
