### ISSUE TITLE
Package Validator - Valid URL is failing

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/home#44]
The `docsUrl` for `bigwig` is failing validation, even though I can open it up fine in my browser.
https://community.chocolatey.org/packages/Bitwig/3.3.7
https://www.bitwig.com/pery/download/14/

I reran the validator, and it was again marked as invalid for the rerun.

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/community-infrastructure/package-validator/-/issues/267) by [Unito](https://www.unito.io/learn-more)

**Comment by gep13** [comment]
Including @Schroedingers-Cat for reference

**Comment by gep13** [comment]
@Schroedingers-Cat do you know if this URL always went to an online PDF, or did it go to something else previously?

I have validated that this URL causes a problem when running through the current infrastructure.  We might be able to work around this, but I would like to understand if something has changed here before going much further with this.  Thanks

**Comment by Schroedingers-Cat** [comment]
It has always been pointing to a PDF.  

I uploaded package v3.3.6 just two minutes before v3.3.7, both with the same link to the manual. v3.3.6 went through, but v3.3.7 got rejected because of the same link.

**Comment by gep13** [comment]
@Schroedingers-Cat in that time frame, nothing has changed in the package-validator rules or setup, they are exactly the same.

This points at "something" changing on the vendor website, which the package-validator rules doesn't work with anymore.  I honestly don't know what this would be, and I am also not in a position to spend much time looking into this currently 😢

**Comment by AdmiringWorm** [comment]
@gep13 the only thing that I noticed about the URL to the PDF document is that:

1. Sometimes it can take quite some time to load (so that could have prevented the validator)
2. It only supports TLS 1.2 and TLS 1.3 ciphers
3. Sets the `Content-Encoding` to `plainbinary` (which I have never seen before, so including it just in case).

There doesn't look like anything else that could be a problem.

**Comment by Schroedingers-Cat** [comment]
Since I have no control over the server hosting these files, I'm not able to change any of these things about the URL. Still, if the link is valid, the validator shouldn't fail.  
Is it possible to get more info from the validator on why it decides to mark the URL as invalid?

**Comment by gep13** [comment]
@Schroedingers-Cat Looking at the logs for this package, I am seeing the following:

```
2021-05-03 07:01:29,182 60 [INFO ] - ========== Bitwig v3.3.7 ==========
2021-05-03 07:01:29,182 60 [INFO ] - Bitwig (Install) v3.3.7 found for review.
2021-05-03 07:01:29,182 60 [INFO ] - Validating Package: Bitwig Version: 3.3.7
2021-05-03 07:02:05,932 60 [INFO ] - Running validation rules...
2021-05-03 07:02:38,306 60 [WARN ] - Error validating Url https://www.bitwig.com/pery/download/14 - A task was canceled.
2021-05-03 07:02:40,321 60 [INFO ] - Bitwig v3.3.7 FAILED validation.
2021-05-03 07:02:40,321 60 [INFO ] - Updating database for Bitwig v3.3.7 with results (package failed requirements).
```

This happens when the timeout, which is currently set for 30 seconds, elapses.

Waiting more than 30 seconds to validate a URL doesn't seem like the correct approach to me, so i don't think extending the timeout is something that we can look at.

The options going forward would be to provide an exemption from the package validator for this package version (this would need to be done each package version), or remove the docs URL from the nuspec (perhaps putting it into the description instead).

**Comment by Schroedingers-Cat** [comment]
When I click on the link [https://www.bitwig.com/pery/download/14 ](https://www.bitwig.com/pery/download/14), it takes me 8 seconds to download the entire file. I'm not sure how there can be a timeout when validating the link.  

I can move the link to the manual into the description unless you're out of ideas why the validator isn't progressing with the link validation.

**Comment by TheCakeIsNaOH** [comment]
I am seeing similar symptoms with another package:
https://community.chocolatey.org/packages/soundswitch/5.9.0

I'm not sure if this is the same issue or not, feel free to split this off into a new issue if this is different.

CC @teknowledgist

**Comment by gep13** [comment]
@TheCakeIsNaOH that is a different issue. Running that through package-validator, the server is responding with a status code of `ServiceUnavailable` which then fails this check:

```
return response.StatusCode == System.Net.HttpStatusCode.OK;
```

**Comment by gep13** [comment]
@Schroedingers-Cat I believe that I may have a solution to this problem, but won't know for certain until tomorrow at the earliest.  Will keep you posted.

@TheCakeIsNaOH @teknowledgist can one of you create another issue regarding the other package?  Thanks!

**Comment by TheCakeIsNaOH** [comment]
#50

**Comment by gep13** [comment]
@Schroedingers-Cat I have just pushed out a new version of package-validator which appears to address this issue, as I have put https://community.chocolatey.org/packages/Bitwig/3.3.7 back through the validator, and it has succeeded.  Thanks for bearing with us through this!
