### ISSUE TITLE
[Website] Package statistics not showing properly on chocolatey.org

### ISSUE THREAD

**Issue by AlexandraIsabel** [chocolatey/home#5]
The statistic for Unique packages/total packages shows just `/` (screenshot below).
![image](https://user-images.githubusercontent.com/7906551/107442856-be7fff00-6b05-11eb-91b2-1432454065e4.png)
Upon inspection in the browser console, this is likely due to the CORS policy on `https://community.chocolatey.org/stats` not allowing for requests originating from `https://chocolatey.org` or `https://www.chocolatey.org` (screenshot from browser console below).
![image](https://user-images.githubusercontent.com/7906551/107443144-41a15500-6b06-11eb-86c7-7b9416c62c99.png)

**Comment by gep13** [comment]
@AlexandraIsabel thank you for taking the time to report this issue.

A new version of the site has been published which addresses this issue.
