### ISSUE TITLE
Package Validator - Valid URLs failing validation

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/home#60]
There are URLs which open in Firefox, but are being marked as invalid by the validator.

Package affected:
https://community.chocolatey.org/packages/tidal/2.28.0.0

URLs affected:
https://tidal.com/terms
https://tidal.com/whatistidal
https://tidal.com/

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/package-validator/-/issues/273) by [Unito](https://www.unito.io)

**Comment by tunisiano187** [comment]
I have the same issue

Package affected : 
https://community.chocolatey.org/packages/deepl/2.5.1

URLs affected:
https://www.deepl.com/en/pro-license#free
https://www.deepl.com/

**Comment by niks255** [comment]
Mine is failing as well https://community.chocolatey.org/packages/vkmessenger
Not sure which URL is affected

**Comment by SebastianK90** [comment]
There are some more packages affected:
https://community.chocolatey.org/packages/telegram
https://community.chocolatey.org/packages/telegram.portable
https://community.chocolatey.org/packages/telegram.install

**Comment by JPRuskin** [comment]
[VKMessenger](https://community.chocolatey.org/packages/vkmessenger/5.3.2) is also affected with the following URLs: 
- https://vk.com/terms
- https://vk.com/messenger

**Comment by TheCakeIsNaOH** [comment]
Another:
https://airsdk.harman.com/runtime
https://community.chocolatey.org/packages/AdobeAIR/33.1.1.674

**Comment by gep13** [comment]
Well, this was another fun little adventure!

If you do a HEAD request to this URL: https://vk.com/messenger you will get the famous 418 I'ma teapot response:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418

The validator wasn't handling this, but it should be now!

**Comment by gep13** [comment]
@TheCakeIsNaOH @SebastianK90 @tunisiano187 @niks255 I believe I have addressed all the URL's that are mentioned in this issue, with the exception of this one:

https://airsdk.harman.com/runtime

When passed through the validator, this is resulting in a Status Code of 404 Not Found, and when I open it in the browser, although the page renders, I also see a 404 response there:

![2021-11-25_08-03-42](https://user-images.githubusercontent.com/1271146/143402777-1718ece6-72fb-453c-aafb-043da6f711f4.png)

This strikes me as a bug in the website itself, not with the package validation rules that we have in place.  As such, I am going to close out this issue, we can open another one for that specific URL.
