### ISSUE TITLE
Community package repository has no packages

### ISSUE THREAD

**Issue by Robulane** [chocolatey/home#63]
The following API returns 0 packages: https://community.chocolatey.org/api/v2/

I cannot install community packages. Getting the following error:
The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'

**Comment by vexx32** [comment]
<https://community.chocolatey.org/api/v2/Packages()> correctly returns packages for me. Which package(s) are you trying to install?

Would be good if you could provide a log file as well so we can rule out as much as possible. 🙂

**Comment by Robulane** [comment]
Nvm, I did a typo and when I was querying the packages I didn't add /Packages() suffix. The issue can be closed. Thank you! :)

**Comment by vexx32** [comment]
Glad you got it sorted! 💖
