### ISSUE TITLE
Adopt SemVer v2 for Package Versioning

### ISSUE THREAD

**Issue by Starz0r** [chocolatey/home#69]
Right now, the site seems to be using [SemVer v1](https://semver.org/spec/v1.0.0.html). While that's not a big issue, I'd say it's worth upgrading to [SemVer v2](https://semver.org/spec/v2.0.0.html). Not so recently, I tried uploading a valid SemVer package that looked something like “v1.0.0-rc.1” and had a rather vague error when it failed. When I tracked it down to the version tag, that's when I realized the site didn't fully support SemVer. 

Upgrading would allow for more flexible versioning, such as:
- 1.0.0-alpha.2
- 3.3.0-alpha.1.22.45
- 9.8.0-alpha.4.5.6
- 2.5.4-alpha.77.2.13.0
- 1.2.3-pre.4+build.5

This only made me slightly more confused when I saw that the actual [SemVer v2 specification](https://semver.org/spec/v2.0.0.html) has been around since Early 2014 — Late 2013. So, I'm not entirely sure what the actual issue or reason is, but I did feel the need to bring it up.

**Comment by TheCakeIsNaOH** [comment]
I think it needs to be supported in choco as well, it's not just a repository thing:
https://github.com/chocolatey/choco/issues/508

**Comment by savornicesei** [comment]
This should also be added to documentation. There's no mention how the package name must be to publish a prerelease version.

**Comment by TheCakeIsNaOH** [comment]
@savornicesei If there is something missing from the documentation, can you file a new issue over at the docs repository:
https://github.com/chocolatey/docs/issues

**Comment by pauby** [comment]
As there is nothing more to do here, I'm going to go ahead and close this. We can always reopen again later if needed.
