### ISSUE TITLE
Document shimming by putting binaries in architecture specific folders

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/home#71]
Create documentation for this: https://github.com/chocolatey/choco/issues/1365

**Comment by TheCakeIsNaOH** [comment]
Wrong repo, delete this

**Comment by gep13** [comment]
@TheCakeIsNaOH For future reference, we can move issues between repositories, so just let us know if this happens again, and we can get it moved.

**Comment by gep13** [comment]
A new issue was created here: https://github.com/chocolatey/docs/issues/229 to cover this work.
