### ISSUE TITLE
Choco installer is not respecting the ChocolateyInstall environment variable

### ISSUE THREAD

**Issue by chughesvf** [chocolatey/home#75]
A recent change to install.ps1 at 'https://chocolatey.org/install.ps1' is causing the following error at the final step of installation.  Unfortunately I have been unable to locate the repository for the install.ps1 script to do more analysis. I was able to reproduce the error using psexec and running as the 'Network Service' account our build agents use. Seems this occurred right around September 2nd and there may have been a new version of Choco released that day. Chocolatey does install perfectly fine to the expected location, it is the last step that uses an unexpected location ( The default chocolatey location where we have chocolatey installed for local server package management, not build management ).

```
Ensuring chocolatey.nupkg is in the lib folder

Copy-Item : Access to the path 'C:\ProgramData\chocolatey\lib\chocolatey\chocolatey.nupkg' is denied.
At C:\windows\ServiceProfiles\NetworkService\Desktop\choco_install.ps1:558 char:1
+ Copy-Item -Path $file -Destination $nupkg -Force -ErrorAction Silentl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.CopyItemCommand```

**Comment by gep13** [comment]
@vexx32 are you in a position to take a look at this?

/cc @pauby

**Comment by vexx32** [comment]
This is the relevant section from the script:

```ps1
Write-Host 'Ensuring Chocolatey commands are on the path'
$chocoInstallVariableName = "ChocolateyInstall"
$chocoPath = [Environment]::GetEnvironmentVariable($chocoInstallVariableName)

if (-not $chocoPath) {
    $chocoPath = "$env:ALLUSERSPROFILE\Chocolatey"
}

if (-not (Test-Path ($chocoPath))) {
    $chocoPath = "$env:PROGRAMDATA\chocolatey"
}

$chocoExePath = Join-Path $chocoPath -ChildPath 'bin'

# Update current process PATH environment variable if it needs updating.
if ($env:Path -notlike "*$chocoExePath*") {
    $env:Path = [Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine);
}

Write-Host 'Ensuring chocolatey.nupkg is in the lib folder'
$chocoPkgDir = Join-Path $chocoPath -ChildPath 'lib\chocolatey'
$nupkg = Join-Path $chocoPkgDir -ChildPath 'chocolatey.nupkg'

if (-not (Test-Path $chocoPkgDir -PathType Container)) {
    $null = New-Item -ItemType Directory -Path $chocoPkgDir
}

Copy-Item -Path $file -Destination $nupkg -Force -ErrorAction SilentlyContinue
```

It looks like we do look for the environment variable here, so I'm not entirely sure what's going on here. Seems like we're getting a null/empty string result back from that query, so it's using a fallback... Not sure why that query wouldn't work, possibly we need to manually refresh the environment variable values from the machine/user environment before querying that, or just look up that value in the machine or user contexts rather than the local process.

**Comment by chughesvf** [comment]
@vexx32  can you confirm if there were any changes to the install script as a result of the latest upgrade?

**Comment by vexx32** [comment]
There were no changes to the install script in this most recent upgrade as far as I'm aware. It was last changed a handful of months ago, to my memory, well before the 0.11.0 or 0.11.1 release.

**Comment by chughesvf** [comment]
Super odd. Perhaps it is environment related but we also haven't made changes in ~9 months and suddenly it is failing on 3/3 build servers.

**Comment by chughesvf** [comment]
I ran some more tests injecting some messaging in the install.ps1 script and have found that despite trying to set the ChocolateyInstall environment variable as either user or process level the line 

```$chocoPath = [Environment]::GetEnvironmentVariable($chocoInstallVariableName)```

always returned C:\ProgramData\chocolatey. There was a system level environment variable that set ChocolateyInstall to the default location. I am unsure where this environment variable came from but once I removed it the code would use the User defined environment variable instead.

Currently it is unclear which cause our issue. The permission change to the default chocolatey install folder or the addition of the system environment variable. 

I cannot say for sure which variable should be sourced in which order when installing ( User, Process or Machine ) but for sure this variable is not consistent from start to finish of the installer since installation was happening in the right location, but the final copy of the chocolatey.nupkg was not.

I think there is likely an oversight here in the consistency. Let me know if you need any more information.

**Comment by chughesvf** [comment]
A further comment. After removing the system environment variable for "ChocolateyInstall" it keeps reappearing. We believe it may be the puppet forge chocolatey module that is being used for on server package management that is putting it back in place.

Any feedback would be greatly appreciated. My deduction of at this point is two fold:

1. it may be impossible to have a core chocolatey version installed that manages packages on our servers in tandem with separate versions for build agents to use for actually packaging packages for consumption
2. chocolatey doesn't seem to like allowing installation by the unprivileged accounts running the build agents services run under since 95% of the way through installation the installer flips back to the system level environment variable.

**Comment by vexx32** [comment]
I think we'd have to dig into the install script in the chocolatey package itself, this feels like it involves more than just the raw install script that gets pulled down from chocolatey.org itself. I'll have a bit of a poke as I'm able to see what's going on.

If I understand you correctly, your particular use case is wanting to have side-by-side installations of Chocolatey itself? And effectively changing where to install each one by setting the `ChocolateyInstall` variable before starting the installation?

And the reason for this is that you want "isolated" versions of chocolatey which handle just purely the packaging of new packages?

To my current understanding, the installer wasn't really designed with that kind of use case in mind -- but that doesn't necessarily mean it's something we can't at least enable, even if it's not a use case we fully support or test heavily. Can I ask why you have a need to maintain separate installations here? What does that give you that doesn't work well with just a single system-level Chocolatey install?

It sounds like the install script in the Chocolatey package might not be checking user-scope settings for `ChocolateyInstall` and is probably only looking in the machine scope. That's something we could probably sort out to some extent.

**Comment by chughesvf** [comment]
Installing in non-default location as a **unprivileged user** results in the final step of copying "chocolatey.nupkg" to default to the **system assigned environment** variable instead of user/process assigned. All the rest of the installation works as expected.

Currently our chocolatey for **server package management** on that machine is pinned to an older version due to a bug. We allow our build agents that are using chocolatey for **packaging our build packages** during pipelines to install any version they want.

We run 4 build agents per server. 

For sure I can tell you the installer switches which environment scoped variable midway through installation. This would appear to be a non-issue if you didn't have more than one version of chocolatey on the box. Other than this issue we had this working for the last year but I presume it was never working "fully" as expected and may have been grabbing the nupkg file from the wrong location all along.

**Comment by vexx32** [comment]
Gotcha, that makes sense. Is that a bug in Choco itself you're referring to (if so, mind linking the issue)?

I'll set aside some time to dig into the Chocolatey installer and see if I can see what's up. 🙂

**Comment by chughesvf** [comment]
@vexx32  I am starting to think that perhaps something in choco is now constantly placing the ChocolateyInstall environment variable at the system level. Each time I delete it, it returns after one successful build and defaults to the standard location. 

Be that as it may, if the installer would just use the same scoped environment variable throughout this would also solve the issue as well.

**Comment by chughesvf** [comment]
I am motioning to our team that we will have to make some changes on our devops agents to fix this. We haven't passed an automated build since Sept 1. Currently getting our builds to pass requires us to login to multiple build servers and delete environment variables that keep re-appearing pointing to the wrong directory then re-running the ADO pipeline manually. This has also delayed a substantial project of overhauling our devops environment. 

Once we work around this the need for your effort may be moot and if you wish i will just close the ticket at that point.

**Comment by pauby** [comment]
@chughesvf Based on your last comment, are you happy for this issue to be closed?

**Comment by chughesvf** [comment]
I do think it is some kind of bug given it used to work, and setting the ENV isn't respected. but for now I am happy to close the case since its impact has been remediated in our environment
