### ISSUE TITLE
Package Validator - Check for packages build with licensed features

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/home#76]
The Package Validator should check for packages build using licensed features (from the upcoming v3 release) and fail those packages.

Reasoning:
I have noticed a couple of packages that I think were created with package builder given the differences in template format from open source choco. In the future, any (new) packages from the package builder will fail the verifier as it runs open source choco. However, that may not be ideal, as the package install failure would be in the gist, and there may be maintainers asking for help as to why the package is failing. Thus, it would be good for the validator to give an explicit error message.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/package-validator/-/issues/270) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
@pauby adding you here for visibility.  I agree with @TheCakeIsNaOH here, and think we need to get this added prior to the release of v3.0.0 of Chocolatey Licensed.

**Comment by pauby** [comment]
I agree that we should look at this, but I don't think there will be time to add it to Package Validator prior to the release.
