### ISSUE TITLE
Chocolatey closing as soon as it opens. How to fix this?

### ISSUE THREAD

**Issue by neethunath** [chocolatey/home#77]

**Comment by neethunath** [comment]
It is like crashing. It closes as soon as I open it.

**Comment by TheCakeIsNaOH** [comment]
Chocolatey is a command line program, not a GUI program. So if you are double-clicking on choco.exe, then it is expected that it does not open up a GUI.

Have you tried opening an administrator command prompt, and running `choco --help`?

**Comment by gep13** [comment]
@neethunath I am going to go ahead and close this issue out, as I suspect what @TheCakeIsNaOH has said is what was happening.

If this is something else, then feel free to respond to this issue.
