### ISSUE TITLE
Unable to publish package, cannot locate package on Chocolatey community packages

### ISSUE THREAD

**Issue by asheroto** [chocolatey/home#78]
I've created a package for [sftpgo](https://github.com/drakkan/sftpgo) but when I publish it I get the error

```
An error has occurred. It's possible the package version already exists on the repository.
```

[Package source](https://github.com/asheroto/ChocolateyPackages/tree/master/SFTPGo)

I actually started this package 5 months ago but got this error back then, so I figured somebody else was working on it.  I've seen no progress since then, so I'm not sure what's going on?  When searching for `sftpgo` on the website it cannot be found, it cannot be found with `choco search sftpgo`, and a direct URL where it should be returns 404.

Author of software actually [prompted me about it](https://github.com/drakkan/sftpgo/issues/575#issuecomment-944884387).

**Comment by TheCakeIsNaOH** [comment]
Try looking in the logs to confirm, but I think this is because the description contains more than 4000 characters. 
https://github.com/chocolatey/choco/issues/2007

**Comment by gep13** [comment]
@asheroto I have just checked the logs, and this is indeed the case:

> A nuget package's Description property may not be more than 4000 characters long.

You will need to shorten the description before you will be able to push it to community.chocolatey.org.

I am going to go ahead and close out this issue.

**Comment by asheroto** [comment]
Thanks!
