### ISSUE TITLE
Invalid link to /account/Profiles from /packages

### ISSUE THREAD

**Issue by bandwith** [chocolatey/home#79]
On the page https://community.chocolatey.org/packages

exists the element
 `<a class="nav-link" href="/account">
            <span class="fas fa-cogs" alt="Account"></span>
            <p class="mb-0">Account</p>
        </a>`

 Which results in a 404

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1097) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
@bandwith I believe I am right in saying that you are referring to this link:

```


<a class="nav-link" href="/account/Profiles">
  <span class="fas fa-user-alt" alt="Profile"></span>
  <p class="mb-0">Profile</p>
</a>
```

Since the `/account` link is valid.

**Comment by bandwith** [comment]
Yes, you are correct. It's been a busy few days. Sorry for the incorrect information.

For a point of information, my connection originated from an IPv6 host.

**Comment by bandwith** [comment]
To be a bit more specific in this, the invalid link is presented to `user-authenticated`

`<li class="nav-item user-authenticated">
        <a class="nav-link" href="/account/Profiles">
            <span class="fas fa-user-alt" alt="Profile"></span>
            <p class="mb-0">Profile</p>
        </a>
    </li>`

**Comment by st3phhays** [comment]
I have looked into this a bit, and it seems to be a cache issue that will likely need to be handled with JS. If you navigate to the second page of package results, the Profile link should work. Can you confirm that @bandwith?

I've also noticed the "Log Off" button does not work on the first page of package results, but does indeed work on every other page. This might be a little more tricky to tackle.

cc @gep13

**Comment by bandwith** [comment]
@st3phhays as I haven't looked into this in some time and have not able to replicate the problem today, I'd consider this resolved.

**Comment by tunisiano187** [comment]
The problem still exists
i went to a package never visited and i have the same issue, so i don't think it's linked to caching.
I hope it's helping

**Comment by pauby** [comment]
This does look to be broken for me too when I'm logged in (https://community.chocolatey.org/account/Profiles)

![image](https://user-images.githubusercontent.com/12760779/152587960-25d6aa11-1249-49ab-bcc3-f48959ed9e89.png)

**Comment by bandwith** [comment]
Looks like it's been reported broken previously. 

#17

**Comment by pauby** [comment]
@st3phhays Could you have a look at this?
