### ISSUE TITLE
Package count issues - caching?

### ISSUE THREAD

**Issue by sampctech** [chocolatey/home#8]
Last Friday I was browsing through the package list on https://chocolatey.org/ and noticed that when I would go from the current page to the next, the content would sometimes be the same, even though the page # in the address bar did change. I would also go from D to G to C to D again when going forward. Going back a page was even worse.
Today I thought I would try again & noticed that it says "There are 8384 Community Maintained Packages" when Popularity is selected, but when changed to A-Z that # changes to 8190. When left as Popularity, page 2 shows 4952 & when refreshing the page, jumps to 8191. Chocolatey GUI isn't even giving an option to go to a 2nd page any more. CGUI as well as the page through Chrome, Firefox, Brave & Waterfox all the same experience on 2 different Windows 10 machine, 1909 & 20H2. I even tried the page on my ArchLinux machine with the same outcome.
Not sure what is going on, but please resolve.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1153) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
@sampctech sorry to hear that you are having problems.

What you are describing is likely the known issue with the caching solution that is currently implemented on chocolatey.org.  These problems typically sort themselves out after a period of time, but there is no immediate solution to this problem, until some infrastructure changes are made to the site.

**Comment by unforgettableid** [comment]
Dear @corbob:  Thank you for the message you sent me!

A.)  May I ask which caching solution is used at chocolatey.org?

B.)  Do you know why the caching solution causes the issue?

C.)  It's been a couple of years so far.  Does anyone yet have any guess as to when the necessary infrastructure changes might happen?

**Comment by riedel** [comment]
If #225 was also a caching issue then this is a really weird one. If the search is actually cached, why would the cache update only add one package and then another one. If the query was just cached it would seem to me that once the cache invalidates itself both package should appear and not one by one. I experienced first no results for podman, then only podman machine and then podman desktop. Also trying other queries. Just commenting in case there is more to it.

**Comment by pauby** [comment]
@riedel We can go into all the gory details, but it'd bore you. How it should work is 99% of the time. How it doesn't work is 1%. And that 1% of the time it causes weird issues like you're seeing.

We are working on replacing the caching that is used, however, we have had to delay the implementation due to other priorities. But it is coming.
