### ISSUE TITLE
Problem with search bar 

### ISSUE THREAD

**Issue by marlonklc** [chocolatey/home#87]
Hi Folks,

today I decided to search on site (https://community.chocolatey.org/packages) by term "mouse", but happen timeout (status 524).

I know, this very crazy, but it's true.

**on search**
![image](https://user-images.githubusercontent.com/9343013/143296743-049aaba0-da60-49a6-bf0a-58fcce51ec9a.png)

**after search**
![image](https://user-images.githubusercontent.com/9343013/143296832-8ae2c325-16ab-4452-9fbb-edcbfe737411.png)

**Comment by pauby** [comment]
I'm assuming this was a one off and we can close it?

**Comment by pauby** [comment]
I'm going to go ahead and close this issue, but we can reopen it if necessary.
