### ISSUE TITLE
Can't install when the system drive is not C:, and the installation already exists in C: for another Windows install

### ISSUE THREAD

**Issue by Archomeda** [chocolatey/home#9]
I know it's an odd case to not having C: as the system drive, but I somehow ended up with this setup when installing a second Windows in dual boot in order to keep the old Windows installation until I decide to delete it.

In any case, the installation of chocolatey fails when the running Windows OS is not installed on the C: drive, but (in my case) installed on the F: drive. I have an old Windows install on C: on dual boot, and that Windows install does have chocolatey installed, and therefore the install fails with the message that chocolatey is already installed, despite it not being installed in the current running Windows installation.

I looked at the install.ps1 file, and it seems that you're hardcoding the C:\ProgramData\Chocolatey path once, and another one for $env:SYSTEMDRIVE\ProgramData\Chocolatey.
I believe the first one is causing the issues. However, can both be changed to use $env:PROGRAMDATA instead?

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/chocolatey-software/community.chocolatey.org/-/issues/1056) by [Unito](https://www.unito.io/learn-more)

**Comment by gep13** [comment]
@Archomeda thank you for taking the time to report this.

This does indeed look like an oversight in some of the changes that we recently made to the installation script.  I am going to get @vexx32 to confirm, and update if required, and we will push out a new version of the site.

**Comment by vexx32** [comment]
Heh. Yeah, that makes sense. We'll get this sorted out. Thanks for bringing it to our attention! 💖

**Comment by ferventcoder** [comment]
`$env:SystemDrive` I believe is what we used to use (if that helps @vexx32).

**Comment by gep13** [comment]
@Archomeda thanks again for raising this issue.  A new version of the install script has been deployed, which should now address the issue.  Let us know if you have any follow up questions.
